import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: false,
  clean: true,
  external: [
    'hono',
    '@hono/zod-validator',
    'zod',
    '@aah/database',
    '@aah/auth',
    '@aah/api-utils',
    '@aah/config',
    '@aah/ai',
    'ai',
    '@ai-sdk/openai',
    '@ai-sdk/anthropic',
    'openai',
    '@anthropic-ai/sdk',
    'langchain',
    '@langchain/core',
    '@langchain/openai',
    '@langchain/anthropic',
    '@langchain/community',
    'tiktoken',
    'compromise',
    'jsonwebtoken',
    'crypto-js',
  ],
});
